#!/bin/bash
DAEMONUSER=${DAEMONUSER:-mongodb}
if [ ! -d /var/lib/mongod ]; then
  mkdir -p /var/lib/mongodb && chown mongodb:mongodb /var/lib/mongodb
fi
if [ ! -d /var/log/mongod ]; then
  mkdir -p /var/log/mongodb && chown mongodb:mongodb /var/log/mongodb
fi

touch /var/run/mongodb.pid
chown $DAEMONUSER /var/run/mongodb.pid

ENABLE_MONGOD="yes"
CONF=/etc/mongod.conf
DAEMON=/usr/bin/mongod
DAEMONUSER=${DAEMONUSER:-mongodb}

if [ -f /etc/default/mongod ]; then . /etc/default/mongod; fi

# Handle NUMA access to CPUs (SERVER-3574)
# This verifies the existence of numactl as well as testing that the command works
NUMACTL_ARGS="--interleave=all"
if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
then
  NUMACTL="$(which numactl) -- $NUMACTL_ARGS"
  DAEMON_OPTS=${DAEMON_OPTS:-"--config $CONF"}
else
  NUMACTL=""
  DAEMON_OPTS="-- "${DAEMON_OPTS:-"--config $CONF"}
fi

if [ "x$ENABLE_MONGOD" = "xyes" ]
then
  exec start-stop-daemon --start \
      --chuid $DAEMONUSER \
      --pidfile /var/run/mongodb.pid \
      --make-pidfile \
      --exec $NUMACTL $DAEMON $DAEMON_OPTS --fork
fi

